global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape métricas do OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: '/metrics'

  # Scrape métricas do Jaeger (telemetria interna)
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:8888']
    metrics_path: '/metrics'

